image: php:7.0

stages:
  - deploy
  
before_script:
- apt-get update && apt-get install -qqy git unzip
- curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
- curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
- chmod a+x /usr/local/bin/codecept
- composer install
  
deploy:
  stage: deploy
  script:
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - docker
  when: manual
    