stages:
  - prepare
  - deploy
  
before_script:
- composer install

build-test:
  stage: prepare
  script:
   - docker build -t deployer ~/deployer/.
  tags:
   - docker 
  
deploy:
  stage: deploy
  script:
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - docker
  image: deployer
  when: manual
    