stages:
  - deploy
  
before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.pumpic.com

deploy:
  stage: deploy
  script:
    - composer install
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - deployer
  when: manual