image: deployer

stages:
  - deploy
  
before_script:
- composer install
  
deploy:
  stage: deploy
  script:
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - deployer
  when: manual
    