stages:
  - deploy
  
build-test:
  stage: prepare
  script:
   - docker build -t deployer ~/deployer/.
  tags:
   - shell 

deploy:
  stage: deploy
  script:
    - composer install
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - docker
  when: manual
    