image: registry.pumpic.com/deployer

stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  script:
    - composer update
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - deployer
  when: manual