image: php:7.0

stages:
  - deployer_setup

deployer setup:
  stage: deployer_setup
  script:
    - git clone git@gitlab.dizboard.com:pumpic/deployer-recipes.git
    - cp ./deployer-recipes/dep /usr/local/bin/dep
    - chmod +x /usr/local/bin/dep
    - dep
  only:
    - master
  tags:
    - docker
  when: manual
    