image: registry.pumpic.com/deployer

stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh

deploy:
  stage: deploy
  script:
    - composer install
    - ./vendor/boomers/deployer-recipes/dep
  only:
    - master
  tags:
    - deployer
  when: manual