version: '2'
services:
    application:
        build: compose/application
        command: sh -c "cd public && env php -d xdebug.idekey=$$XDEBUG_KEY -d xdebug.remote_host=$$XDEBUG_HOST -S 0.0.0.0:8000 index.php"
        user: www-data
        ports:
            - "8100:8000"
            - "8101:9000"
        volumes:
            - .:/code
            - ~/.ssh:/home/www-data/.ssh
        environment:
            - DOMAIN=http://localhost:8100
            - DOMAIN_STATIC=http://localhost:8100/static
            #- DOMAIN_COOKIE=localhost
            - SUPPORT_EMAIL=support@google.com
            - URL_DEMO=http://google.com/demo
            - URL_REGISTRATION=http://google.com/registration
            #- SECURE_CONNECTION=1
            - S3_KEY=AKIAJCULQL4O4GXAD4WQ
            - S3_SECRET=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
            - S3_BUCKET=incoming-files
            - S3_REGION=us-west-2
            - CLOUD_FRONT_DOMAIN=http://media.pumpic.com/
            - CLOUD_FRONT_KEYPAIR_ID=APKAJGHJLY2FNTE5A62Q
            - DB_MAIN_HOST=188.40.64.2
            - DB_MAIN_DATABASE=main_test
            - DB_MAIN_USER=dev_test
            - DB_MAIN_PASSWORD=hEcLTXHGWTpY
            - DB_DATA_1_HOST=188.40.64.2
            - DB_DATA_1_DATABASE=data_test
            - DB_DATA_1_USER=dev_test
            - DB_DATA_1_PASSWORD=hEcLTXHGWTpY
            - XDEBUG_KEY=netbeans-xdebug
            - XDEBUG_HOST=localhost