<script
        id="fsc-api"
        src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.7.3/fastspring-builder.min.js"
        type="text/javascript"
        data-storefront="pumpic.onfastspring.com/popup-pumpic"
        data-data-callback="dataCallbackFunction"
        data-before-requests-callback="beforeRequestsCallbackFunction"
        data-decorate-callback="decorateURLFunction"
        data-popup-event-received="popupEventReceived"
        {*data-debug="true"*}
>
</script>